create TABLE MEAL(
	MEAL_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	RESTAURANT_NAME VARCHAR(50),
	RESTAURANT_ID VARCHAR(50),
	TOKEN_VALUE INT,
	PURCHASE_DATE TIMESTAMP,
	EXPIRATION_DATE TIMESTAMP,
	MEAL_DESCRIPTION VARCHAR(30),
	TTL INT
);

create TABLE PROVIDER(
	PROVIDER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	RESTAURANT_NAME VARCHAR(50),
	RESTAURANT_ID VARCHAR(50)
);


create TABLE IF NOT EXISTS `LiveMealRepo` (
  `MealID` INT NOT NULL,
  `ProviderID` INT NULL,
  `TokenValue` INT NULL,
  `PurchaseValue` DECIMAL NULL,
  `StartTimeAvailable` TIMESTAMP NULL,
  `EndTimeAvailable` TIMESTAMP NULL,
  `TTL` INT NULL,
  `DPS` INT NULL DEFAULT 1,
  PRIMARY KEY (`MealID`))
ENGINE = InnoDB